backend:
  # Use netlify identity as backend
  name: "git-gateway"
  branch: "main"
  repo: "https://github.com/AXYS-Creative/essence"
media_folder: "src/static/img"
public_folder: "/static/img"
site_url: https://essentialism.netlify.app # On admin login page, this adds a 'go back to site' link. Also added in the corner when logged in.
display_url: https://essentialism.netlify.app # In admin dashboard, this addes the URL in the corner. Used with 'preview_path' for collection viewing.
logo_url: https://essentialism.netlify.app/static/img/admin-logo.svg # On admin login page, this adds a custom logo.

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts/blog"
    preview_path: "posts/blog/{{filename}}/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["popular", "general", "physical", "emotion", "finance"]
      - label: "Cover Image" # Only seems to work with .md collections
        name: "image"
        widget: "image"
        required: false
  - name: "podcast"
    label: "Podcast"
    folder: "src/posts/podcast"
    preview_path: "posts/podcast/{{filename}}/"
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "i.e. Episode #3 - Consumerism",
        }
      - {
          label: "Title Short",
          name: "title_short",
          widget: "string",
          hint: "i.e. Consumerism",
        }
      - {
          label: "Episode",
          name: "episode",
          widget: "string",
          hint: "i.e. 003",
        }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Guest", name: "guest", widget: "string" }
      - { label: "Video Poster", name: "poster", widget: "image" }
      - {
          label: "Video Embed",
          name: "video_embed",
          widget: "string",
          hint: "Copy the iframe embed from a youtube video and paste it here.",
        }
      - { label: "Episode Recap", name: "body", widget: "markdown" }
      - {
          label: "Quote",
          name: "quote",
          widget: "text",
          hint: "Don't add quotation marks around the quote. These are already added in the code.",
        }
      - { label: "Quote Image", name: "quote_image", widget: "image" }
      - widget: select
        label: "Quote Side"
        name: "quote_side"
        multiple: false
        create: false
        options: ["left", "right"]
        required: true
        hint: "Place text to the left or right of the section"
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["popular", "general", "physical", "emotion", "finance"]
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Cover Image"
        name: "image"
        widget: "image"
        required: false
  - name: "books"
    label: "Books"
    label_singular: "Book"
    folder: "src/posts/books"
    preview_path: "posts/books/{{filename}}/"
    create: true
    editor:
      preview: false
    fields:
      - { name: "title", label: "Book Title", widget: "string" }
      - { name: "description", label: "Book Description", widget: "text" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "date", label: "Publish Date", widget: "datetime" }
      - { name: "img_list", label: "List Image", widget: "image" }
      - {
          name: "img_list_description",
          label: "List Image Description",
          widget: "string",
          required: true,
          hint: "For the Archive Page. Required for SEO and accessibility. Keep it brief.",
        }
      - { name: "img_full", label: "Full Image", widget: "image" }
      - {
          name: "img_full_description",
          label: "Full Image Description",
          widget: "string",
          required: true,
          hint: "Required for SEO and accessibility. Keep it brief.",
        }
      - { name: "img_side", label: "Side Image", widget: "image" }
      - {
          name: "img_side_description",
          label: "Side Image Description",
          widget: "string",
          required: true,
          hint: "Required for SEO and accessibility. Keep it brief.",
        }
      - {
          name: "body",
          label: "Author Bio",
          widget: "markdown",
          modes: ["raw"],
          sanitize_preview: true,
        }
      - { name: "author_portrait", label: "Author Portrait", widget: "image" }
      - {
          name: "author_portrait_description",
          label: "Author Portrait Description",
          widget: "string",
          required: true,
          hint: "Required for SEO and accessibility. Keep it brief.",
        }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["popular", "general", "physical", "emotion", "finance"]
      - label: "Cover Image"
        name: "image"
        widget: "image"
        required: false
  - name: "about_page"
    label: "About Page"
    description: >
      Modify content for the 'About' Page.
      This is the description
    files:
      - name: "collage_images"
        label: "Collage Images"
        file: "src/_data/collage_images.yaml"
        preview_path: "/about"
        editor:
          preview: true
        fields:
          - name: "images"
            label: "Images"
            label_singular: "Image"
            widget: "list"
            collapsed: false
            fields:
              - widget: select
                name: "tags"
                label: "Placement Helper"
                multiple: false
                options:
                  [
                    "Column 1",
                    "Column 2",
                    "Column 3",
                    "Column 4",
                    "Column 5",
                    "Mobile Column",
                  ]
                default: ["Add Column"]
                hint: "Non-functional, simply a visual aid while in the admin dashboard."
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "description",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                  hint: "Required for SEO and accessibility. Keep it brief.",
                }
      - name: "recorded_growth"
        label: "Recorded Growth"
        file: "src/_data/recorded_growth.yaml"
        preview_path: "/about#recorded-growth"
        editor:
          preview: true
          previewStyles: "/static/styles/styles.css"
        fields:
          - name: "image"
            label: "Cover Image"
            widget: "image"
            required: false
          - name: "growth_stats"
            label: "Growth Stats"
            label_singular: "Growth Stat"
            widget: "list"
            collapsed: false
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "numbers", label: "Numbers", widget: "string" }
      - name: "team_portraits"
        label: "Team Portraits"
        file: "src/_data/team_portraits.yaml"
        preview_path: "/about#our-team"
        editor:
          preview: true
        fields:
          - name: "images"
            label: "Portrait Images"
            label_singular: "Image"
            widget: "list"
            collapsed: false
            fields:
              - {
                  name: "caption",
                  label: "Image Caption",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "description",
                  label: "SEO Description",
                  widget: "string",
                  required: true,
                  hint: "Required for SEO and accessibility. Keep it brief.",
                }
  - name: "resources_page"
    label: "Resources Page"
    files:
      - name: "resource_list"
        label: "Resource List"
        file: "src/_data/resource_list.yaml"
        preview_path: "/resources#resources-list"
        editor:
          preview: false
        fields:
          - name: "services"
            label: "Services"
            label_singular: "Service"
            widget: "list"
            collapsed: false
            fields:
              - label: "Category"
                name: "tag"
                widget: select
                multiple: false
                options: ["Physical", "Emotional", "Financial"]
                default: ["Add Category"]
              - { name: "title", label: "Title", widget: "string" }
  - name: "contact_page"
    label: "Contact Page"
    files:
      - name: "office_locations"
        label: "Office Locations"
        file: "src/_data/office_locations.yaml"
        preview_path: "/contact#office-locations"
        editor:
          preview: true
        fields:
          - name: "locations"
            label: "Location Details"
            label_singular: "Location"
            widget: "list"
            collapsed: false
            fields:
              - { label: "City", name: "city", widget: "string" }
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "alt",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                  hint: "Required for SEO and accessibility. Keep it brief.",
                }
              - { name: "address_1", label: "Adress, street", widget: "string" }
              - {
                  name: "address_2",
                  label: "Adress, city / state",
                  widget: "string",
                }
              - { label: "Phone", name: "phone", widget: "string" }
  - name: "partials"
    label: "Partials"
    description: >
      Reusable components throughout the site.
    files:
      - name: "partial_resources"
        label: "Resources"
        file: "src/_data/partial_resources.yaml"
        preview_path: "/#essence-resources"
        editor:
          preview: true
        fields:
          - name: "categories"
            label: "Categories"
            label_singular: "Category"
            widget: "list"
            collapsed: false
            max: 3
            fields:
              - name: "tag"
                label: "Tag"
                widget: select
                multiple: false
                required: true
                options: ["Physical", "Emotional", "Financial"]
                default: ["Add Tag"]
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "alt",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                  hint: "Required for SEO and accessibility. Keep it brief.",
                }
      - name: "partial_carousel"
        label: "Carousel"
        file: "src/_data/partial_carousel.yaml"
        preview_path: "/#essence-media-praises"
        editor:
          preview: false
        fields:
          - name: "testimonials"
            label: "Testimonials"
            label_singular: "Testimonial"
            widget: "list"
            collapsed: false
            max: 5
            fields:
              - {
                  name: "name",
                  label: "Name",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "role",
                  label: "Role",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "quote",
                  label: "Quote",
                  widget: "text",
                  required: true,
                  hint: "Please don’t wrap the quote in quotation marks, they’re already included.",
                }
              - { name: "img", label: "Image", widget: "image", required: true }
  - name: "settings"
    label: "Settings"
    description: >
      Website general settings and SEO configs.
    files:
      - name: "social_media"
        label: "Social Media"
        file: "src/_data/social_media.yaml"
        fields:
          - name: "links"
            label: "Nav Items"
            label_singular: "Nav Item"
            widget: "list"
            collapsed: false
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
              - { name: "src", label: "Image Source", widget: "image" }
      - name: "site_navigation"
        label: "Site Navigation"
        file: "src/_data/site_navigation.yaml"
        fields:
          - name: "links"
            label: "Links"
            label_singular: "Link"
            widget: "list"
            collapsed: false
            max: 8
            fields:
              - {
                  name: "title",
                  label: "Title",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "img_src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "img_alt",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                  hint: "Required for SEO and accessibility. Keep it brief.",
                }
      - name: "open_graph"
        label: "Open Graph Protocol"
        file: "src/_data/open_graph.yaml"
        fields:
          - name: "item"
            label: "Items"
            label_singular: "item"
            widget: "list"
            collapsed: false
            max: 1
            fields:
              - {
                  name: "img_src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
