backend:
  # Use netlify identity as backend
  name: "git-gateway"
  branch: "main"
media_folder: "src/static/img"
public_folder: "/static/img"
site_url: https://essentialism.netlify.app # On admin login page, this adds a 'go back to site' link
display_url: https://essentialism.netlify.app # In admin dashboard, this addes the URL in the corner
logo_url: https://essentialism.netlify.app/static/img/admin-logo.svg # On admin login page, this adds a custom logo

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts/blog"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["popular", "general", "physical", "emotion", "finance"]
  - name: "podcast"
    label: "Podcast"
    folder: "src/posts/podcast"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title Short", name: "title_short", widget: "string" }
      - { label: "Episode", name: "episode", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Guest", name: "guest", widget: "string" }
      - { label: "Video Poster", name: "poster", widget: "image" }
      - { label: "Video Embed", name: "video_embed", widget: "string" }
      - { label: "Episode Recap", name: "body", widget: "markdown" }
      - { label: "Quote", name: "quote", widget: "string" }
      - { label: "Quote Image", name: "quote_image", widget: "image" }
      - widget: select
        label: "Quote Side"
        name: "quote_side"
        multiple: false
        create: false
        options: ["left", "right"]
        required: true
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["popular", "general", "physical", "emotion", "finance"]
      - { label: "Publish Date", name: "date", widget: "datetime" }
  - name: "books"
    label: "Books"
    label_singular: "Book"
    folder: "src/posts/books"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Poster", name: "src", widget: "image" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["popular", "general", "physical", "emotion", "finance"]
  - name: "about_page"
    label: "About Page"
    description: >
      Modify content for the 'About' Page.
      This is the description
    files:
      - name: "collage_images"
        label: "Hero Collage"
        file: "src/_data/collage_images.yaml"
        editor:
          preview: true
        thumbnail: "/img/collage-1a.webp"
        fields:
          - name: "images"
            label: "Images"
            label_singular: "Image"
            widget: "list"
            collapsed: false
            fields:
              - widget: select
                name: "tags"
                label: "Placement Helper"
                multiple: false
                options:
                  [
                    "Column 1",
                    "Column 2",
                    "Column 3",
                    "Column 4",
                    "Column 5",
                    "Mobile Column",
                  ]
                default: ["Add Column"]
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "description",
                  label: "Description",
                  widget: "string",
                  required: true,
                }
      - name: "recorded_growth"
        label: "Recorded Growth"
        file: "src/_data/recorded_growth.yaml"
        editor:
          preview: true
          previewStyles: "/static/styles/styles.css"
        fields:
          - name: "growth_stats"
            label: "Growth Stats"
            label_singular: "Growth Stat"
            widget: "list"
            collapsed: false
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "numbers", label: "Numbers", widget: "string" }
      - name: "team_portraits"
        label: "Team Portraits"
        file: "src/_data/team_portraits.yaml"
        editor:
          preview: true
        fields:
          - name: "images"
            label: "Portrait Images"
            widget: "list"
            collapsed: false
            fields:
              - {
                  name: "caption",
                  label: "Image Caption",
                  widget: "string",
                  required: true,
                }
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "description",
                  label: "SEO Description",
                  widget: "string",
                  hint: "Describe the image",
                  required: true,
                }
  - name: "resources_page"
    label: "Resources Page"
    files:
      - name: "resource_list"
        label: "Resource List"
        file: "src/_data/resource_list.yaml"
        editor:
          preview: false
        fields:
          - name: "services"
            label: "Services"
            label_singular: "Service"
            widget: "list"
            collapsed: false
            fields:
              - label: "Category"
                name: "tag"
                widget: select
                multiple: false
                options: ["Physical", "Emotional", "Financial"]
                default: ["Add Category"]
              - { name: "title", label: "Title", widget: "string" }
  - name: "contact_page"
    label: "Contact Page"
    files:
      - name: "office_locations"
        label: "Office Locations"
        file: "src/_data/office_locations.yaml"
        editor:
          preview: true
        fields:
          - name: "locations"
            label: "Location Details"
            label_singular: "Location"
            widget: "list"
            collapsed: false
            fields:
              - { label: "City", name: "city", widget: "string" }
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "alt",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                }
              - { name: "address_1", label: "Adress, street", widget: "string" }
              - {
                  name: "address_2",
                  label: "Adress, city / state",
                  widget: "string",
                }
              - { label: "Phone", name: "phone", widget: "string" }
  - name: "partials"
    label: "Partials"
    files:
      - name: "partial_resources"
        label: "Resources"
        file: "src/_data/partial_resources.yaml"
        editor:
          preview: true
        fields:
          - name: "categories"
            label: "Categories"
            label_singular: "Category"
            widget: "list"
            collapsed: false
            max: 3
            fields:
              - name: "tags"
                label: "Category"
                widget: select
                multiple: false
                required: true
                options: ["Physical", "Emotional", "Financial"]
                default: ["Add Category"]
              - {
                  name: "src",
                  label: "Image Source",
                  widget: "image",
                  required: true,
                }
              - {
                  name: "alt",
                  label: "Image Description",
                  widget: "string",
                  required: true,
                }
  - name: "settings"
    label: "Settings"
    files:
      - name: "social_media"
        label: "Social Media"
        file: "src/_data/social_media.yaml"
        fields:
          - name: "links"
            label: "Nav Items"
            label_singular: "Nav Item"
            widget: "list"
            collapsed: false
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
              - { name: "src", label: "Image Source", widget: "image" }
      - name: "nav_images"
        label: "Navigation Images"
        file: "src/_data/nav_images.yaml"
        fields:
          - name: "images"
            label: "Nav Images"
            label_singular: "Nav Image"
            widget: "list"
            collapsed: false
            max: 8
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "src", label: "Image Source", widget: "image" }
